language: vi
pipeline:
- name: vietTokenizer
  intent_tokenization_flag: true
  intent_split_symbol: _
- name: RegexFeaturizer
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  batch_strategy: sequence
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 50
- name: MappingPolicy
- name: FormPolicy
- name: FallbackPolicy
  nlu_threshold: 0.6
  core_threshold: 0.3
  fallback_action_name: utter_fallback
